# Generated by Django 3.0.7 on 2020-06-19 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Client name')),
                ('email', models.EmailField(max_length=254, verbose_name='Client email')),
                ('content', models.TextField(max_length=10000, verbose_name='Message from client')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Time of message')),
            ],
        ),
    ]
