# Generated by Django 3.0.6 on 2020-06-02 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('title_description', models.TextField(blank=True, null=True)),
                ('title_button', models.CharField(default='Join', max_length=50)),
                ('title_btn_url', models.CharField(blank=True, max_length=50, null=True)),
                ('content', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
