# Generated by Django 3.0.6 on 2020-06-04 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20200604_0517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='layout',
        ),
    ]
